# Generated by Django 4.0.1 on 2022-02-14 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cityonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIN', models.CharField(max_length=15, unique=True)),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=40)),
                ('img_verify', models.CharField(default='none', max_length=100, null=True)),
                ('add_on', models.DateTimeField(auto_now=True)),
                ('datenaissance', models.DateTimeField()),
                ('adresse_now', models.CharField(max_length=60)),
                ('sexe', models.CharField(max_length=10)),
                ('etat_civil', models.CharField(max_length=10)),
                ('Verified_Information', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on', models.DateTimeField(auto_now=True)),
                ('Done', models.BooleanField()),
                ('CIN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.cityonne')),
                ('Res', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-add_on'],
            },
        ),
        migrations.CreateModel(
            name='Type_Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeCommand', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=130, null=True)),
                ('add_on', models.DateTimeField(auto_now=True)),
                ('Res', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien_file', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=2000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('CIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.demande')),
            ],
        ),
        migrations.AddField(
            model_name='demande',
            name='TypeCommand',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TypeCmd', to='home.type_command'),
        ),
    ]
