# Generated by Django 4.0.1 on 2022-02-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_type_command_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityonne',
            name='phone',
            field=models.CharField(default='none', max_length=15),
        ),
    ]
