# Generated by Django 4.0.1 on 2022-02-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_cityonne_datenaissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityonne',
            name='et_de',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='cityonne',
            name='file_de',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='demande',
            name='Done',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
