# Generated by Django 4.0.1 on 2022-02-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cityonne_et_de_cityonne_file_de_alter_demande_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityonne',
            name='adresse_back',
            field=models.CharField(default='none', max_length=40),
        ),
    ]
