# Generated by Django 4.0.1 on 2022-02-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cityonne_adresse_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityonne',
            name='img_verify',
        ),
        migrations.AddField(
            model_name='cityonne',
            name='adresse_back_ar',
            field=models.CharField(default='none', max_length=40),
        ),
        migrations.AddField(
            model_name='cityonne',
            name='et_de_ar',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='cityonne',
            name='file_de_ar',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='cityonne',
            name='nom_ar',
            field=models.CharField(default='none', max_length=40),
        ),
        migrations.AddField(
            model_name='cityonne',
            name='prenom_ar',
            field=models.CharField(default='none', max_length=40),
        ),
        migrations.AlterField(
            model_name='cityonne',
            name='nom',
            field=models.CharField(default='none', max_length=40),
        ),
    ]
