# Generated by Django 4.0.1 on 2022-02-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_cityonne_img_verify_cityonne_adresse_back_ar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='file',
        ),
    ]
