# Generated by Django 4.0.1 on 2022-02-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityonne',
            name='adresse_now_ar',
            field=models.CharField(default='none', max_length=160),
        ),
        migrations.AlterField(
            model_name='cityonne',
            name='adresse_now',
            field=models.CharField(max_length=160),
        ),
    ]
